var face =[
  {value:"( .-. )"},
  {value:"( .o.)"},
  {value:"( `·´ )"},
  {value:"( ° ͜ ʖ °)"},
  {value:"( ͡° ͜ʖ ͡°)"},
  /*{value:"( ⚆ _ ⚆ )"},*/
  {value:"( ︶︿︶)"},
  {value:"( ﾟヮﾟ)"},
  {value:"(\\/)(°,,,°)(\\/)"},
  {value:"(¬_¬)"},
  {value:"(¬º-°)¬"},
  {value:"(¬‿¬)"},
  {value:"(°ロ°)☝"},
  {value:"(´・ω・)っ"},
  {value:"(ó ì_í)"},
  {value:"(ʘᗩʘ')"},
  {value:"(ʘ‿ʘ)"},
  {value:"(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄"},
  {value:"(͡° ͜ʖ ͡°)"},
  {value:"(ಠ_ಠ)"},
  {value:"(ಠ‿ಠ)"},
  {value:"(ಠ⌣ಠ)"},
  {value:"(ಥ_ಥ)"},
  {value:"(ಥ﹏ಥ)"},
  {value:"(ง ͠° ͟ل͜ ͡°)ง"},
  {value:"(ง ͡ʘ ͜ʖ ͡ʘ)ง"},
  {value:"(ง •̀_•́)ง"},
  {value:"(ง'̀-'́)ง"},
  {value:"(ง°ل͜°)ง"},
  {value:"(ง⌐□ل͜□)ง"},
  {value:"(ღ˘⌣˘ღ)"},
  {value:"(ᵔᴥᵔ)"},
  {value:"(•ω•)"},
  {value:"(•◡•)/"},
  {value:"(⊙ω⊙)"},
  {value:"(⌐■_■)"},
  {value:"(─‿‿─)"},
  {value:"(╯°□°）╯"},
  {value:"(◕‿◕)"},
  {value:"(☞ﾟ∀ﾟ)☞"},
  {value:"(❍ᴥ❍ʋ)"},
  {value:"(っ◕‿◕)っ"},
  {value:"(づ｡◕‿‿◕｡)づ"},
  {value:"(ノಠ益ಠ)ノ"},
  {value:"(ノ・∀・)ノ"},
  {value:"(；一_一)"},
  {value:"(｀◔ ω ◔´)"},
  {value:"(｡◕‿‿◕｡)"},
  {value:"(ﾉ◕ヮ◕)ﾉ"},
  {value:"*<{:¬{D}}}"},
  {value:"=^.^="},
  {value:"t(-.-t)"},
  {value:"| (• ◡•)|"},
  {value:"~(˘▾˘~)"},
  {value:"¬_¬"},
  {value:"¯(°_o)/¯"},
  {value:"¯\_(ツ)_/¯"},
  {value:"°Д°"},
  {value:"ɳ༼ຈل͜ຈ༽ɲ"},
  {value:"ʅʕ•ᴥ•ʔʃ"},
  {value:"ʕ´•ᴥ•`ʔ"},
  {value:"ʕ•ᴥ•ʔ"},
  {value:"ʕ◉.◉ʔ"},
  {value:"ʕㅇ호ㅇʔ"},
  {value:"ʕ；•`ᴥ•´ʔ"},
  {value:"ʘ‿ʘ"},
  {value:"͡° ͜ʖ ͡°"},
  {value:"ζ༼Ɵ͆ل͜Ɵ͆༽ᶘ"},
  {value:"Ѱζ༼ᴼل͜ᴼ༽ᶘѰ"},
  {value:"ب_ب"},
  {value:"٩◔̯◔۶"},
  {value:"ಠ_ಠ"},
  {value:"ಠoಠ"},
  {value:"ಠ~ಠ"},
  {value:"ಠ‿ಠ"},
  {value:"ಠ⌣ಠ"},
  {value:"ಠ╭╮ಠ"},
  {value:"ರ_ರ"},
  {value:"ง ͠° ل͜ °)ง"},
  {value:"๏̯͡๏﴿"},
  {value:"༼ ºººººل͟ººººº ༽"},
  {value:"༼ ºل͟º ༽"},
  {value:"༼ ºل͟º༼"},
  {value:"༼ ºل͟º༽"},
  {value:"༼ ͡■ل͜ ͡■༽"},
  {value:"༼ つ ◕_◕ ༽つ"},
  {value:"༼ʘ̚ل͜ʘ̚༽"},
  {value:"ლ(´ڡ`ლ)"},
  {value:"ლ(́◉◞౪◟◉‵ლ)"},
  {value:"ლ(ಠ益ಠლ)"},
  {value:"ᄽὁȍ ̪őὀᄿ"},
  {value:"ᔑ•ﺪ͟͠•ᔐ"},
  {value:"ᕕ( ᐛ )ᕗ"},
  {value:"ᕙ(⇀‸↼‶)ᕗ"},
  {value:"ᕙ༼ຈل͜ຈ༽ᕗ"},
  {value:"ᶘ ᵒᴥᵒᶅ"},
  {value:"‎‎(ﾉಥ益ಥ）ﾉ"},
  {value:"≧☉_☉≦"},
  {value:"⊙▃⊙"},
  {value:"⊙﹏⊙"},
  {value:"┌( ಠ_ಠ)┘"},
  {value:"╚(ಠ_ಠ)=┐"},
  {value:"◉_◉"},
  {value:"◔ ⌣ ◔"},
  {value:"◔̯◔"},
  {value:"◕‿↼"},
  {value:"◕‿◕"},
  {value:"☉_☉"},
  {value:"☜(⌒▽⌒)☞"},
  {value:"☼.☼"},
  {value:"♥‿♥"},
  /*{value:"⚆ _ ⚆"},*/
  {value:"✌(-‿-)✌"},
  {value:"〆(・∀・＠)"},
  {value:"ノ( º _ ºノ)"},
  {value:"ノ( ゜-゜ノ)"},
  {value:"ヽ( ͝° ͜ʖ͡°)ﾉ"},
  {value:"ヽ(`Д´)ﾉ"},
  {value:"ヽ༼° ͟ل͜ ͡°༽ﾉ"},
  {value:"ヽ༼ʘ̚ل͜ʘ̚༽ﾉ"},
  {value:"ヽ༼ຈل͜ຈ༽ง"},
  {value:"ヽ༼ຈل͜ຈ༽ﾉ"},
  {value:"ヽ༼Ὸل͜ຈ༽ﾉ"},
  {value:"ヾ(⌐■_■)ノ"},
  {value:"(･◡･๑)"},
  {value:"﴾͡๏̯͡๏﴿"},
  {value:"｡◕‿◕｡"},
  {value:"ʕノ◔ϖ◔ʔノ"},
  {value:"ಠ_ರೃ"},
  {value:"(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू)"},
  /*{value:"(ꈨຶꎁꈨຶ)۶”"},*/
  {value:"(°᷄д°᷅)"},
  {value:"(۶ૈ ۜ ᵒ̌▱๋ᵒ̌ )۶ૈ=͟͟͞͞ ⌨"},
  {value:"₍˄·͈༝·͈˄₎◞ ̑̑ෆ⃛"},
  {value:"(*ﾟO ∀ O͠)ﾉ❣"},
  {value:"٩(･ัε･ั )۶"},
  {value:"ヘ（。□°）ヘ"},
  /*{value:"˓˓(ृ　 ु ॑꒳’)ु(ृ’꒳ ॑ ृ　)ु˒˒˒"},*/
  /*{value:"꒰✘Д✘◍꒱"},*/
  {value:"૮( ᵒ̌ૢཪᵒ̌ૢ )ა"},
  {value:"“ψ(｀∇´)ψ"},
  {value:"ಠﭛಠ"},
  {value:"(๑>ᴗ<๑)"},
  /*{value:"(۶ꈨຶꎁꈨຶ )۶ʸᵉᵃʰᵎ"},*/
  {value:"٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ"},
  {value:"(oT-T)尸"},
  {value:"(✌ﾟ∀ﾟ)☞"},
  {value:"ಥ‿ಥ"},
  {value:"ॱ॰⋆(˶ॢ‾᷄﹃‾᷅˵ॢ)"},
  {value:"┬┴┬┴┤  (ಠ├┬┴┬┴"},
  {value:"( ˘ ³˘)♥"},
  {value:"Σ (੭ु ຶਊ ຶ)੭ु⁾⁾"},
  {value:"(⑅ ॣ•͈ᴗ•͈ ॣ)"},
  {value:"ヾ(´￢｀)ﾉ"},
  {value:"(•̀o•́)ง"},
  {value:"(๑•॒̀ ູ॒•́๑)"},
  /*{value:"⚈้̤͡ ˌ̫̮ ⚈้̤͡"},*/
  {value:"=͟͟͞͞ =͟͟͞͞ ﾍ( ´Д`)ﾉ"},
  {value:"(((╹д╹;)))"},
  {value:"•̀.̫•́✧"},
  {value:"(ᵒ̤̑ ₀̑ ᵒ̤̑)"},
  {value:"\_(ʘ_ʘ)_/"}
];

var x = Math.floor((Math.random() * face.length) + 0);
document.getElementById('content').innerHTML= face[x].value;

function next(){
  var x = Math.floor((Math.random() * face.length) + 0);
  document.getElementById('content').innerHTML= face[x].value;
}
